### ISSUE TITLE
 [🐛] Documentation invalid for custom images

### ISSUE THREAD

**Issue by JamesCullum** [bkimminich/pwning-juice-shop#49]
# :bug: Bug report

## Description

The documentation about [customization](https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/part1/customization.html) asks the user to put all images for custom products into the location `/app/public/images/products`. 

However this static folder is [currently disabled](https://github.com/bkimminich/juice-shop/blob/master/server.js#L182) and files there are ignored.

Instead the files now need to be put into `/juice-shop/frontend/dist/frontend/assets` according to the line below.

### Is this a regression?

Yes, it was disabled by [this commit](https://github.com/bkimminich/juice-shop/commit/b9e3f7ff6a4468cad45a83bafc38f9dc712e55a0) in June 2018. However, the documentation was wrong back then as well, as it wasnt `/app`, but `/juice-shop/app`.

## :microscope: Minimal Reproduction

Configure a custom product and follow the documentation by putting an image into `/app/public/images/products` - the image will not be found

## :fire: Exception or Error

No error, images are simply not visible

## :deciduous_tree: Your Environment

Docker image v9.0.1

**Comment by bkimminich** [comment]
Thanks for the PR, just merged it! I'd recommend you to use just a URL for custom images, and they will be downloaded into the mentioned folder automatically. That's the easiest way. Otherwise they have to be provided in that specific folder e.g. in your Docker image - allowing a custom asset folder will not be implemented in Juice Shop as the HTTP download option makes that kind of obsolete.

I could imagine allowing `file://...` URLs but only if they work with the download mechanism out of the box as it is today. If you want to try that, feel free to do and send a PR for it to the main repo.

**Comment by JamesCullum** [comment]
We are using a custom docker image to load our own yml and images. To prevent it from downloading the images for every execution or the images getting removed online, it makes sense to be able to mount them directly. Thanks for the merge!

**Comment by bkimminich** [comment]
You'd have to put them into the right folder as a separate step in your Dockerfile then. I just tried `file://` but https://www.npmjs.com/package/download doesn't seem to accept that as a protocol.

**Comment by JamesCullum** [comment]
Yeah, this is my dockerfile at the moment, which works good.

```
FROM bkimminich/juice-shop:v9.0.1

COPY juice-shop/config /juice-shop/config
COPY --chown=juicer:root juice-shop/frontend /juice-shop/frontend/dist/frontend
```
